{{- if not .Values.config.adminPassword.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "checkmk.fullname" . }}-secrets
  labels:
    {{- include "checkmk.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.adminPassword.passwordKey }}: {{ .Values.config.adminPassword.value | default "changeme" | b64enc }}
{{- end }}
